#!/bin/bash
set -eu
cd "$( dirname "${BASH_SOURCE[0]}" )/.."

if [[ -z "${CONTINUOUS_INTEGRATION-}" ]] ; then
	echo 'error: this script must be run on CI platform, determined by non-empty value in $CONTINUOUS_INTEGRATION' >&2
	exit 1
fi

if [[ -n "$test_group" ]] ; then
	echo "skip ci-coverage while executing test_group=$test_group" >&2
	exit 0
fi

codecov --flags=$(echo $python |tr -d -- '-.')
