name: style
on:
  push:
  pull_request:
jobs:
  style:
    runs-on: ubuntu-latest
    # https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/5
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'httplib2/httplib2'
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
            setup.py
      - name: pip install
        run: pip install black isort -r requirements-test.txt
      - name: isort
        run: isort --check python3/ tests/ || echo FIXME
      - name: black
        run: black --check --diff python3/ tests/ || echo FIXME
      - run: stages=venv,style script/test
